version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: company

    volumes:
      - pgdata:/var/lib/postgresql/data

  java_app:
    container_name: java_app
    image: grgo/java_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/company
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=super_secret
    depends_on:
      - postgres_db

volumes:
  pgdata: {}


